/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;
import java.io.*;
import java.nio.file.Files;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Mitchell
 */
public class EventFrame extends javax.swing.JFrame {

    /**
     * Creates new form TestFrame
     */
    public EventFrame() {
        this.setUndecorated(false);
        this.setExtendedState(EventFrame.MAXIMIZED_BOTH);
        initComponents();
        //this.setTitle();
        addButton.setVisible(false);
        editButton.setVisible(false);
        bookButton.setVisible(false);
        modifyButton.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createDialog = new javax.swing.JDialog();
        nameField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        typeField = new javax.swing.JTextField();
        typeLabel = new javax.swing.JLabel();
        capacityField = new javax.swing.JTextField();
        capacityLabel = new javax.swing.JLabel();
        priceField = new javax.swing.JTextField();
        priceLabel = new javax.swing.JLabel();
        promotionField = new javax.swing.JTextField();
        promotionLabel = new javax.swing.JLabel();
        dateField = new javax.swing.JTextField();
        dateLabel = new javax.swing.JLabel();
        descriptionField = new javax.swing.JTextField();
        descriptionLabel = new javax.swing.JLabel();
        createButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        editDialog = new javax.swing.JDialog();
        editnameField = new javax.swing.JTextField();
        editnameLabel = new javax.swing.JLabel();
        edittypeField = new javax.swing.JTextField();
        edittypeLabel = new javax.swing.JLabel();
        editcapacityField = new javax.swing.JTextField();
        editcapacityLabel = new javax.swing.JLabel();
        editpriceField = new javax.swing.JTextField();
        editpriceLabel = new javax.swing.JLabel();
        editpromotionField = new javax.swing.JTextField();
        editpromotionLabel = new javax.swing.JLabel();
        editdateField = new javax.swing.JTextField();
        editdateLabel = new javax.swing.JLabel();
        editdescriptionField = new javax.swing.JTextField();
        editdescriptionLabel = new javax.swing.JLabel();
        editdialogButton = new javax.swing.JButton();
        editcancelButton = new javax.swing.JButton();
        bookingDialog = new javax.swing.JDialog();
        bookingNameLabel = new javax.swing.JLabel();
        bookingTypeLabel = new javax.swing.JLabel();
        bookingCapacityLabel = new javax.swing.JLabel();
        bookingPriceLabel = new javax.swing.JLabel();
        bookingPromotionField = new javax.swing.JTextField();
        bookingPromotionLabel = new javax.swing.JLabel();
        bookingDateLabel = new javax.swing.JLabel();
        bookingDialogButton = new javax.swing.JButton();
        bookingCancelButton = new javax.swing.JButton();
        bookingNumberField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        eventList = new javax.swing.JList<>();
        searchField = new javax.swing.JTextField();
        searchLabel = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        bookButton = new javax.swing.JButton();
        modifyButton = new javax.swing.JButton();

        nameField.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        nameLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        nameLabel.setText("Event Name");

        typeField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        typeLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        typeLabel.setText("Event Type");

        capacityField.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        capacityLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        capacityLabel.setText("Event Capacity");

        priceField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        priceLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        priceLabel.setText("Event Price");

        promotionField.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        promotionLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        promotionLabel.setText("Event Promotion");

        dateField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        dateLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        dateLabel.setText("Event Dates");

        descriptionField.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        descriptionLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        descriptionLabel.setText("Event Description");

        createButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        createButton.setText("Create");
        createButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createButtonMouseClicked(evt);
            }
        });
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout createDialogLayout = new javax.swing.GroupLayout(createDialog.getContentPane());
        createDialog.getContentPane().setLayout(createDialogLayout);
        createDialogLayout.setHorizontalGroup(
            createDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createDialogLayout.createSequentialGroup()
                        .addComponent(descriptionLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(createDialogLayout.createSequentialGroup()
                        .addGroup(createDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLabel)
                            .addGroup(createDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(createDialogLayout.createSequentialGroup()
                                    .addComponent(createButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cancelButton))
                                .addComponent(descriptionField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(createDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(createDialogLayout.createSequentialGroup()
                                        .addGroup(createDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(capacityField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(capacityLabel))
                                        .addGap(88, 88, 88)
                                        .addGroup(createDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(priceLabel)
                                            .addComponent(typeField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(typeLabel)))
                                    .addGroup(createDialogLayout.createSequentialGroup()
                                        .addGroup(createDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(promotionField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(promotionLabel))
                                        .addGap(88, 88, 88)
                                        .addGroup(createDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dateLabel))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        createDialogLayout.setVerticalGroup(
            createDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createDialogLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(createDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(typeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(capacityLabel)
                    .addComponent(priceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(capacityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(promotionLabel)
                    .addComponent(dateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(promotionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(descriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(descriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(createDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createButton)
                    .addComponent(cancelButton))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        editnameField.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        editnameLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        editnameLabel.setText("Event Name");

        edittypeField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        edittypeLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        edittypeLabel.setText("Event Type");

        editcapacityField.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        editcapacityLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        editcapacityLabel.setText("Event Capacity");

        editpriceField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        editpriceLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        editpriceLabel.setText("Event Price");

        editpromotionField.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        editpromotionLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        editpromotionLabel.setText("Event Promotion");

        editdateField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        editdateLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        editdateLabel.setText("Event Dates");

        editdescriptionField.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        editdescriptionLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        editdescriptionLabel.setText("Event Description");

        editdialogButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        editdialogButton.setText("Edit");
        editdialogButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editdialogButtonMouseClicked(evt);
            }
        });
        editdialogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editdialogButtonActionPerformed(evt);
            }
        });

        editcancelButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        editcancelButton.setText("Cancel");
        editcancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editcancelButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout editDialogLayout = new javax.swing.GroupLayout(editDialog.getContentPane());
        editDialog.getContentPane().setLayout(editDialogLayout);
        editDialogLayout.setHorizontalGroup(
            editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editDialogLayout.createSequentialGroup()
                        .addComponent(editdescriptionLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(editDialogLayout.createSequentialGroup()
                        .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editnameLabel)
                            .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(editDialogLayout.createSequentialGroup()
                                    .addComponent(editdialogButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(editcancelButton))
                                .addComponent(editdescriptionField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(editDialogLayout.createSequentialGroup()
                                        .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(editcapacityLabel)
                                            .addComponent(editnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(editcapacityField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(12, 12, 12)
                                        .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(editDialogLayout.createSequentialGroup()
                                                .addGap(76, 76, 76)
                                                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(editpriceLabel)
                                                    .addComponent(edittypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(edittypeLabel)))
                                            .addComponent(editpriceField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(editDialogLayout.createSequentialGroup()
                                        .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(editpromotionField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(editpromotionLabel))
                                        .addGap(88, 88, 88)
                                        .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(editdateField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(editdateLabel))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        editDialogLayout.setVerticalGroup(
            editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editDialogLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editnameLabel)
                    .addComponent(edittypeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edittypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editcapacityLabel)
                    .addComponent(editpriceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editcapacityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editpriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editpromotionLabel)
                    .addComponent(editdateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editpromotionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(editdescriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editdescriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editdialogButton)
                    .addComponent(editcancelButton))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        bookingNameLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bookingNameLabel.setText("Event Name");

        bookingTypeLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bookingTypeLabel.setText("Event Type");

        bookingCapacityLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bookingCapacityLabel.setText("Number of tickets");

        bookingPriceLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bookingPriceLabel.setText("Event Price");

        bookingPromotionField.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        bookingPromotionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingPromotionFieldActionPerformed(evt);
            }
        });

        bookingPromotionLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bookingPromotionLabel.setText("Event Promotion");

        bookingDateLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bookingDateLabel.setText("Event Dates");

        bookingDialogButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bookingDialogButton.setText("Book");
        bookingDialogButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookingDialogButtonMouseClicked(evt);
            }
        });
        bookingDialogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingDialogButtonActionPerformed(evt);
            }
        });

        bookingCancelButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bookingCancelButton.setText("Cancel");
        bookingCancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookingCancelButtonMouseClicked(evt);
            }
        });

        bookingNumberField.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        bookingNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingNumberFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bookingDialogLayout = new javax.swing.GroupLayout(bookingDialog.getContentPane());
        bookingDialog.getContentPane().setLayout(bookingDialogLayout);
        bookingDialogLayout.setHorizontalGroup(
            bookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(bookingDialogLayout.createSequentialGroup()
                        .addComponent(bookingDialogButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bookingCancelButton))
                    .addGroup(bookingDialogLayout.createSequentialGroup()
                        .addGroup(bookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bookingDialogLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(bookingNameLabel)
                                .addGap(138, 138, 138)
                                .addComponent(bookingTypeLabel))
                            .addGroup(bookingDialogLayout.createSequentialGroup()
                                .addGroup(bookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bookingPromotionField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bookingPromotionLabel)
                                    .addComponent(bookingCapacityLabel)
                                    .addComponent(bookingNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(88, 88, 88)
                                .addGroup(bookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bookingPriceLabel)
                                    .addComponent(bookingDateLabel))))
                        .addGap(57, 57, 57)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bookingDialogLayout.setVerticalGroup(
            bookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingDialogLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(bookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookingNameLabel)
                    .addComponent(bookingTypeLabel))
                .addGroup(bookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(bookingDialogLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(bookingPriceLabel)
                        .addGap(33, 33, 33))
                    .addGroup(bookingDialogLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(bookingCapacityLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bookingNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(bookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookingPromotionLabel)
                    .addComponent(bookingDateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookingPromotionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(260, 260, 260)
                .addGroup(bookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookingDialogButton)
                    .addComponent(bookingCancelButton))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        eventList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {  };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        eventList.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                eventListFocusGained(evt);
            }
        });
        eventList.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                eventListComponentShown(evt);
            }
        });
        jScrollPane2.setViewportView(eventList);

        searchLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        searchLabel.setText("Search");

        searchButton.setText("SEARCH");
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonMouseClicked(evt);
            }
        });

        loginButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        loginButton.setText("LOGIN");
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
        });

        usernameLabel.setText("Username");

        passwordLabel.setText("Password");

        editButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        editButton.setText("EDIT EVENT");
        editButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editButtonMouseClicked(evt);
            }
        });

        addButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        addButton.setText("ADD EVENT");
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addButtonMouseClicked(evt);
            }
        });

        bookButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        bookButton.setText("BOOK TICKET");
        bookButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookButtonMouseClicked(evt);
            }
        });

        modifyButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        modifyButton.setText("MODIFY BOOKING");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(passwordLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(addButton)
                                        .addGap(297, 297, 297)
                                        .addComponent(editButton)
                                        .addGap(335, 335, 335))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(bookButton)
                                        .addGap(804, 804, 804))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(465, 465, 465)
                                        .addComponent(modifyButton)
                                        .addGap(335, 335, 335)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(usernameField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(passwordField, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1908, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchLabel))
                        .addGap(0, 506, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(searchLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordLabel))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginButton, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bookButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(editButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modifyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(421, 421, 421))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eventListComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_eventListComponentShown
        // TODO add your handling code here:
        /*eventList.removeAll();
        DefaultListModel listModel = new DefaultListModel();
        
        try {
            BufferedReader br = new BufferedReader(new FileReader("Events.txt"));
            String ln = br.readLine();
            
            while (ln != null)
            {
                listModel.addElement(ln);
                ln = br.readLine();
            }
        }
        catch (IOException e) {
            System.out.println("Error");
        }
        
        eventList.setModel(listModel);*/
    }//GEN-LAST:event_eventListComponentShown

    private void eventListFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_eventListFocusGained
        //TODO add your handling code here:
        
    }//GEN-LAST:event_eventListFocusGained

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked
        // TODO add your handling code here:
        ArrayList adminLogins = new ArrayList();
        String username = usernameField.getText();
        char[] password = passwordField.getPassword();
        String passwordFull = new String(password);
        
        try {
            BufferedReader br = new BufferedReader(new FileReader("Admins.txt"));
            String ln = br.readLine();
            
            while (ln != null)
            {
                String [] split = ln.split(" ");
                adminLogins.add(split[0]);
                adminLogins.add(split[1]);
                ln = br.readLine();
                    
            }
            for (int i = 0; i < adminLogins.size(); i+=2)
            {
                int x = i + 1;
                if (adminLogins.get(i).equals(username) && adminLogins.get(x).equals(passwordFull))
                {
                    addButton.setVisible(true);
                    editButton.setVisible(true);
                    bookButton.setVisible(false);
                    modifyButton.setVisible(false);
                }
                
                if (usernameField.getText().equals("") || passwordField.getText().equals(""))
                {
                    addButton.setVisible(false);
                    editButton.setVisible(false);
                    bookButton.setVisible(true);
                    modifyButton.setVisible(true);
                }
            }
            br.close();
        }
        catch (IOException e) {
            System.out.println("Error");
        }
    }//GEN-LAST:event_loginButtonMouseClicked

    private void addButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseClicked
        // TODO add your handling code here:
        createDialog.pack();
        createDialog.setVisible(true);
        nameField.setText("");
        typeField.setText("");
        capacityField.setText("");
        priceField.setText("");
        promotionField.setText("");
        dateField.setText("");
        descriptionField.setText("");
    }//GEN-LAST:event_addButtonMouseClicked

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createButtonActionPerformed

    private void createButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createButtonMouseClicked
        // TODO add your handling code here:
        try {
            BufferedWriter bw = new BufferedWriter(new FileWriter("Events.txt", true));
            
            String name = nameField.getText();
            String type = typeField.getText();
            String capacity = capacityField.getText();
            String price = priceField.getText();
            String promotion = promotionField.getText();
            String date = dateField.getText();
            String description = descriptionField.getText();
            
            bw.write(name + " " + type + " " + capacity + " " + price + " " + promotion + " " + date + " " + description);
            bw.newLine();
            bw.close();
        }
        
        catch (IOException e) {
            System.out.println("Error");
        }
        createDialog.setVisible(false);
    }//GEN-LAST:event_createButtonMouseClicked

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        // TODO add your handling code here:
        createDialog.setVisible(false);
    }//GEN-LAST:event_cancelButtonMouseClicked

    private void bookButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bookButtonMouseClicked

    private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseClicked
        // TODO add your handling code here:
        String search = searchField.getText();
        DefaultListModel listModel = new DefaultListModel();
        try
            {
                BufferedReader br = new BufferedReader(new FileReader("Events.txt"));
                String ln = br.readLine();

                while (ln != null)
                {
                    String [] split = ln.split(" ");
                    if (split[0].contains(search))
                    {
                        listModel.addElement(ln);
                    }
                    ln = br.readLine();
                }
                
                br.close();
            }
        catch (IOException e)
            {
                System.out.println("Error");
            }
        eventList.setModel(listModel);
    }//GEN-LAST:event_searchButtonMouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        eventList.removeAll();
        DefaultListModel listModel = new DefaultListModel();
        
        try {
            BufferedReader br = new BufferedReader(new FileReader("Events.txt"));
            String ln = br.readLine();
            
            while (ln != null)
            {
                listModel.addElement(ln);
                ln = br.readLine();
            }
        }
        catch (IOException e) {
            System.out.println("Error");
        }
        
        eventList.setModel(listModel);
    }//GEN-LAST:event_formComponentShown

    private void editdialogButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editdialogButtonMouseClicked
        // TODO add your handling code here:
        try         
        {
            //Recreates event with updated info
            BufferedWriter bw = new BufferedWriter(new FileWriter("Events.txt", true));
            
            String name = editnameField.getText();
            String type = edittypeField.getText();
            String capacity = editcapacityField.getText();
            String price = editpriceField.getText();
            String promotion = editpromotionField.getText();
            String date = editdateField.getText();
            String description = editdescriptionField.getText();
            
            bw.write(name + " " + type + " " + capacity + " " + price + " " + promotion + " " + date + " " + description);
            bw.close();
            
            //Deletes old event
            File inputFile = new File("Events.txt");
            File tempFile = new File("temp.txt");
            
            BufferedReader reader = new BufferedReader(new FileReader(inputFile));
            BufferedWriter writer = new BufferedWriter(new FileWriter(tempFile));
            
            String lineToRemove = eventList.getSelectedValue();
            String currentLine;
            
            while((currentLine = reader.readLine()) != null)
            {
                String trimmedLine = currentLine.trim();
                if(trimmedLine.equals(lineToRemove)) continue;
                writer.write(currentLine + System.getProperty("line.separator"));
            }
            writer.close();
            reader.close();
            
            BufferedReader treader = new BufferedReader(new FileReader(tempFile));
            BufferedWriter twriter = new BufferedWriter(new FileWriter(inputFile));
            
            String tcurrentLine;
                        
            while((tcurrentLine = treader.readLine()) != null)
            {
                String trimmedLine = tcurrentLine.trim();
                twriter.write(tcurrentLine + System.getProperty("line.separator"));
            }
            twriter.close();
            treader.close();
            
            
            
        }
        catch (IOException e)
        {
            System.out.println("Error");
        }
        editDialog.setVisible(false);
    }//GEN-LAST:event_editdialogButtonMouseClicked

    private void editdialogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editdialogButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editdialogButtonActionPerformed

    private void editcancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editcancelButtonMouseClicked
        // TODO add your handling code here:
        editDialog.setVisible(false);
    }//GEN-LAST:event_editcancelButtonMouseClicked

    private void editButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonMouseClicked
        // TODO add your handling code here:
        editDialog.pack();
        editDialog.setVisible(true);
        try 
        {
            BufferedReader br = new BufferedReader(new FileReader("Events.txt"));
            LineNumberReader lr = new LineNumberReader(br);
            String x = null;
            
            while ((x = br.readLine()) != null) {
                
                if (x.contains(eventList.getSelectedValue()))
                {
                    String [] split = x.split(" ");
                    editnameField.setText(split[0]);
                    edittypeField.setText(split[1]);
                    editcapacityField.setText(split[2]);
                    editpriceField.setText(split[3]);
                    editpromotionField.setText(split[4]);
                    editdateField.setText(split[5]);
                    editdescriptionField.setText(split[6]);

                }
            
                
            }
            br.close();
            lr.close();
        }
        catch (IOException e)
        {
            System.out.println("Error");
        }
    }//GEN-LAST:event_editButtonMouseClicked

    private void bookingDialogButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingDialogButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingDialogButtonMouseClicked

    private void bookingDialogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingDialogButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingDialogButtonActionPerformed

    private void bookingCancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingCancelButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingCancelButtonMouseClicked

    private void bookingPromotionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingPromotionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingPromotionFieldActionPerformed

    private void bookingNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingNumberFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton bookButton;
    private javax.swing.JButton bookingCancelButton;
    private javax.swing.JLabel bookingCapacityLabel;
    private javax.swing.JLabel bookingDateLabel;
    private javax.swing.JDialog bookingDialog;
    private javax.swing.JButton bookingDialogButton;
    private javax.swing.JLabel bookingNameLabel;
    private javax.swing.JTextField bookingNumberField;
    private javax.swing.JLabel bookingPriceLabel;
    private javax.swing.JTextField bookingPromotionField;
    private javax.swing.JLabel bookingPromotionLabel;
    private javax.swing.JLabel bookingTypeLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField capacityField;
    private javax.swing.JLabel capacityLabel;
    private javax.swing.JButton createButton;
    private javax.swing.JDialog createDialog;
    private javax.swing.JTextField dateField;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField descriptionField;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JButton editButton;
    private javax.swing.JDialog editDialog;
    private javax.swing.JButton editcancelButton;
    private javax.swing.JTextField editcapacityField;
    private javax.swing.JLabel editcapacityLabel;
    private javax.swing.JTextField editdateField;
    private javax.swing.JLabel editdateLabel;
    private javax.swing.JTextField editdescriptionField;
    private javax.swing.JLabel editdescriptionLabel;
    private javax.swing.JButton editdialogButton;
    private javax.swing.JTextField editnameField;
    private javax.swing.JLabel editnameLabel;
    private javax.swing.JTextField editpriceField;
    private javax.swing.JLabel editpriceLabel;
    private javax.swing.JTextField editpromotionField;
    private javax.swing.JLabel editpromotionLabel;
    private javax.swing.JTextField edittypeField;
    private javax.swing.JLabel edittypeLabel;
    private javax.swing.JList<String> eventList;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton modifyButton;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField priceField;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField promotionField;
    private javax.swing.JLabel promotionLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JTextField typeField;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
